# Generated by Django 4.0.1 on 2022-01-09 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelOptions(
            name='shopuserprofile',
            options={'verbose_name': 'профиль пользователя', 'verbose_name_plural': 'профиль пользователя'},
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 12, 19, 45, 379514, tzinfo=utc)),
        ),
    ]
