# Generated by Django 4.0.1 on 2022-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imageproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('vk', models.CharField(max_length=128, verbose_name='vk_com')),
                ('telegram', models.CharField(max_length=128, verbose_name='telegram (только логин, без @)')),
                ('youtube', models.CharField(max_length=128, verbose_name='youtube')),
                ('whatsapp', models.CharField(max_length=128, verbose_name='whatsapp (только номер телефона)')),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
    ]
