# Generated by Django 4.0.1 on 2022-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'иконки социальных сетей'},
        ),
        migrations.AlterField(
            model_name='social',
            name='email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='social',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='social',
            name='telegram',
            field=models.CharField(blank=True, max_length=128, verbose_name='telegram (только логин, без @)'),
        ),
        migrations.AlterField(
            model_name='social',
            name='vk',
            field=models.CharField(blank=True, max_length=128, verbose_name='vk_com'),
        ),
        migrations.AlterField(
            model_name='social',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=128, verbose_name='whatsapp (только номер телефона)'),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.CharField(blank=True, max_length=128, verbose_name='youtube'),
        ),
    ]
